name = "LiteHF"
uuid = "87f02e12-f6bc-4038-9bdd-797fa8455fab"
authors = ["Jerry Ling <proton@jling.dev> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
